### ISSUE TITLE
Revoked binstar token blocks public package

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Platform/anaconda-client#104]
After issue #103 forced me to revoke the binstar token, i ran into this inscrutable error:

```
Fetching packages ...
Error: HTTPError: 401 Client Error: UNAUTHORIZED: https://conda.binstar.org/t/bk-69377d5d-dcc5-41cf-b5e9-04c8a1dc16ba/bkreider/linux-64/muster-service-mongodb-0.0.1-3.tar.bz2
```

That package is public, so there is no reason for it to try and use the binstar token.  Even if it was private, it doesn't say anything about how to refresh my binstar token.  That channel is not in my condarc.

**Comment by drf5n** [comment]
Is it fixed in conda?
