### ISSUE TITLE
Unclear in-line help for "package type" option in "upload" command

### ISSUE THREAD

**Issue by megies** [Anaconda-Platform/anaconda-client#132]
Nowhere in the docs or source I can find information on what the valid options for "package type" in `binstar upload` are. Right now I am led to assume that an arbitrary string can be specified as package type. If there is a list of valid package types it should be mentioned in the command help string..

**Comment by electronwill** [comment]
https://github.com/Anaconda-Server/anaconda-client/blob/develop/binstar_client/utils/detect.py#L84 suggests that the list of valid types might be 'conda' 'pypi' 'r' 'ipynb', and https://github.com/Anaconda-Server/anaconda-client/blob/develop/binstar_client/inspect_package/conda_installer.py suggests that 'installer' and 'file' might also be valid types. Once a developer can give a firm answer here the command help string to fix is at https://github.com/Anaconda-Server/anaconda-client/blob/develop/binstar_client/commands/upload.py#L259 .

**Comment by goanpeca** [comment]
@electronwill can we close this issue? or is there any action item related to it?

**Comment by electronwill** [comment]
Thank you for reminding us @goanpeca -- this has been neglected for too long. We need a developer to answer the question: What are the valid choices for package type with ``anaconda upload -t`` ?

Then I'll put that answer in the docs.

**Comment by goanpeca** [comment]
@electronwill just happened to pass by and fixed this.

The answer is `'ipynb, env'` and now the command should include that in the CLI help

**Comment by electronwill** [comment]
Excellent-- thank you!
