### ISSUE TITLE
Allow public visibility of badges for private package

### ISSUE THREAD

**Issue by FvD** [Anaconda-Platform/anaconda-client#144]
If I try to embed the link to a badge for a private package elsewhere it will give a 404 (authorization error). 

It would be useful to be able to set the visibility of these badges in my package settings, as they are great (and meant for !) project status dashboards where the user should not need to log in to binstar.

**Comment by goanpeca** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #3380](https://github.com/Anaconda-Platform/anaconda-server/issues/3380) via [**ZenHub**](https://www.zenhub.com/)

**Comment by goanpeca** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #3381](https://github.com/Anaconda-Platform/anaconda-server/issues/3381) via [**ZenHub**](https://www.zenhub.com/)
