### ISSUE TITLE
Public page does not show private package correctly

### ISSUE THREAD

**Issue by FvD** [Anaconda-Platform/anaconda-client#145]
On the binstar user page (public acess, no login) the package overview does not filter correctly for the private packages (https://binstar.org/username?filter=private):
-  If there are no public packages, only private packages: the "private tab" will state that there are "no private packages"
-  If there are public packages and no private packages: the "private tab" will list all public packages.
-  If there are public packages and private packages: the "private tab" will list all public packages.

I would expect that the Private tab is either not visible, or states a number of private packages without any further details.

**Comment by goanpeca** [comment]
This is now being tracked in the anaconda cloud private repo
