### ISSUE TITLE
Remove Anaconda-client from readthedocs.org - not being maintained. 

### ISSUE THREAD

**Issue by malev** [Anaconda-Platform/anaconda-client#151]
We shouldn't have 2 places with documentation we won't be able to update both of the at the same time

**Comment by malev** [comment]
https://binstar-client.readthedocs.org/en/latest/

**Comment by tswicegood** [comment]
:+1:

**Comment by malev** [comment]
I wonder if @amfarrell knows about this?

**Comment by amfarrell** [comment]
I don't have any particular knowledge but agree that having the documentation all in one place is in general better than two.

**Comment by malev** [comment]
ok, gonna assign this to me and start the clean up

**Comment by electronwill** [comment]
Oh wow, never knew there was a binstar readthedocs.org site. I'll clean that up and reply here when that's done.

**Comment by stephenakearns** [comment]
@electronwill following up on this one...

**Comment by electronwill** [comment]
@srossross I fixed this on the develop and master branches, but it appears that deploying the new version to binstar-client.readthedocs.org requires using the readthedocs.org account that first set up that site. Do you have that?

**Comment by goanpeca** [comment]
@srossross @electronwill any update on this?

**Comment by electronwill** [comment]
Good point. @srossross before you leave, can you please tell us how to publish to binstar-client.readthedocs.org ?

**Comment by goanpeca** [comment]
@srossross ?

**Comment by goanpeca** [comment]
@electronwill this is the current state of https://binstar-client.readthedocs.io/en/latest/
<img width="793" alt="screen shot 2018-03-19 at 16 11 35" src="https://user-images.githubusercontent.com/3627835/37622660-442b7868-2b90-11e8-98c6-b55d2ea46460.png">

I guess we can close this?

**Comment by electronwill** [comment]
Glad to see it! Yes, we can close this.
