### ISSUE TITLE
Anaconda client erroneously references 'binstar.org' - should point to installed version of AS

### ISSUE THREAD

**Issue by LilaHickey** [Anaconda-Platform/anaconda-client#155]
When the binstar client is configured to use a private Anaconda Server installation:

	hq-dhcp-20-64:mongoengine-0.9.0 lilahickey$ binstar config --set url http://104.131.203.85:8080/api

A bad login attempt still instructs the user to reset their password at binstar.org:

	The action you are performing requires authentication, please sign in:
	Username: LilaHickey
	LilaHickey's Password: 
	[error] Invalid Username password combination, please try again 
	LilaHickey's Password: 
	[error] Invalid Username password combination, please try again 
	LilaHickey's Password: 
	[error] Invalid Username password combination, please try again 
	[BinstarError] Sorry. Please try again (go to https://binstar.org/account/forgot_password to 	reset your password) 
	hq-dhcp-20-64:mongoengine-0.9.0 lilahickey$

**Comment by stephenakearns** [comment]
superceded by #2319
