### ISSUE TITLE
binstar --force upload with token gives [BinstarError] Invalid dist_id

### ISSUE THREAD

**Issue by jchodera** [Anaconda-Platform/anaconda-client#173]
We have an automated build server that builds conda packages and pushes them to our `omnia/openmm-dev` binstar package, but when passing a token (marked below as `****` for security) and using `--force`, these uploads occasionally fail with `Invalid dist_id` errors. 

```
[vagrant@localhost ~]$ binstar -t **** --quiet upload --force -u omnia --channel main miniconda/conda-bld/*/openmm-dev-*.tar.bz2
Using binstar api site https://api.anaconda.org
[warning] Distribution linux-64/openmm-dev-dev-py27_0.tar.bz2 already exists ... removing 
[BinstarError] Invalid dist_id 
```

This issue has only started to appear recently.

**Comment by srossross** [comment]
Thanks for reporting this, I will look into it.

**Comment by jchodera** [comment]
Thanks!

**Comment by stephenakearns** [comment]
fixed before end of year - part of upcoming epic

**Comment by stephenakearns** [comment]
including in new epic - "reenable copy"

**Comment by jchodera** [comment]
Thanks for the update, @stephenakearns!

**Comment by j0hn** [comment]
Closing this along with #133 because couldn't reproduce. Please file a new ticket if occurs again.
