### ISSUE TITLE
`get_binstar` API hard to use outside binstar-cli - need it to be more loosely coupled

### ISSUE THREAD

**Issue by malev** [Anaconda-Platform/anaconda-client#174]
I'm using `binstar` as a library and I can't use a different site (other than anaconda.org) because I can't set it up. `get_binstar` is too tight to the `binstar-cli` behavior https://github.com/Anaconda-Server/binstar/blob/master/binstar_client/utils/__init__.py#L153

**Comment by stephenakearns** [comment]
@malev - can you expand description on this issue = I'm a bit unclear about the use case?

**Comment by stephenakearns** [comment]
Example Use case: conda env and nb_anacondacloud should be able to import binstar and use the commands smoothly. Right now, if you do that you'll need to pass a fake args object.

**Comment by goanpeca** [comment]
The get_server_api, addresses this issue

https://github.com/Anaconda-Platform/anaconda-client/blob/master/binstar_client/utils/__init__.py#L154
