### ISSUE TITLE
Auto-detect bad API urls with AS

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Platform/anaconda-client#206]
It's a common mistake for customers and continuum staff to setup the URL wrong when trying to use anaconda-client with an AS install. (clarification:  for AS you need to add /api to the url but that isn't obvious because the anaconda.org uses subdomains:  api.anaconda.org)

Can AS and anaconda client figure out a way to return a nice message when one sets the API url wrong in anaconda client?  This is such a common error, it would be great if it could fix itself.

**Comment by srossross** [comment]
This can probably be fixed in the same PR as #207
