### ISSUE TITLE
Sort subcommands of `anaconda --help`

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/anaconda-client#218]
Should list the `build` subcommand in `conda server --help`. Maybe this should be optional depending on whether `anaconda-build` is installed or it should explain that it requires `anaconda-build` to be installed to use if it is not already.

**Comment by malev** [comment]
@jakirkham I encourage you to update `anaconda-client` to the latest version and start using the `anaconda` command instead of `conda server`.
On the other hand I do like your suggestion.

**Comment by stephenakearns** [comment]
Hi @malev - I'm a bit unclear on the suggestion here. Is the idea that the help info for Anaconda-Client would point to using the Anaconda Build client?

**Comment by jakirkham** [comment]
@stephenakearns, my thought is that each subcommand has a one line description. There should be one for `build`, as well.

**Comment by srossross** [comment]
@jakirkham If you are not seeing build in the command list of `anaconda --help` then you do not have anaconda-build installed. I am also :+1: on adding a "please run `conda install anaconda-build`" help line if it is not installed.

**Comment by jakirkham** [comment]
That was not true at the time. However, it has since changed. I would like to suggest though that `build` be placed in alphabetical order so that it better follows with the existing sort.

**Comment by goanpeca** [comment]
Well build is no longer a valid command
