### ISSUE TITLE
Create conda-tools meta-package for unified "root-env" common commands

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/anaconda-client#236]
I hijacked @msarahan 's narrow issue around `conda-env` being a `root`-env-only package and turned it into a discussion around combining functionality into the `conda` package.  I will try to keep this discussion focused on my specific interest in `anaconda-client`.

Original issue: https://github.com/conda/conda-env/issues/179

@teoliphant and @ilanschnell I can express the issue from a different angle.  `conda-build`, `conda-env`, and `anaconda-client` could all be independent packages but the cross-linking of dependencies and typical use cases means to me that they need to be special cased in such a way that I'd like to propose we have a `conda-tools` meta-package that contains all of these pieces and is handled in a uniform way. This would move to a world where people don't `conda update conda` but instead `conda update conda-tools` so they get the whole set (base, build, env, client) updated together.

We can return to @msarahan 's issue title of "conda-env should only be in root env" (paraphrased): IMO, the same holds true for `anaconda-client`.  I want to be able to do operations like "login" and "upload" and "download" with Anaconda Cloud from any environment.  Right now I have to install `anaconda-client` into every environment in order to do that, and then can get version skew (even if I automate this by adding `anaconda-client` to my `create_default_packages` section of my `.condarc`).  That is Bad with a capital B.

Each of these packages that I'm proposing as part of the `conda-tools` meta package needs to be installed once, with cooperating versions, in the `root` env, and automatically accessible in all non-root envs (the same way `conda` is), and (I would argue) blocked from being installed in non-root envs.

My most recent example of this:

``` bash
(r3)ijstokes@petawawa commands $ anaconda login
-bash: anaconda: command not found

(r3)ijstokes@petawawa commands $ source activate root
discarding /Users/ijstokes/anaconda/envs/r3/bin from PATH
prepending /Users/ijstokes/anaconda/bin to PATH

(root)ijstokes@petawawa commands $ anaconda login
Using anaconda-server api site https://api.anaconda.org
Username:
```

@csoja and @stephenakearns mentioned as I believe this is part of improved user experience and unifed Anaconda Platform experience.

**Comment by ijstokes** [comment]
And more variations on this:

```bash
(r3)ijstokes@petawawa commands $ anaconda login
-bash: anaconda: command not found

(r3)ijstokes@petawawa commands $ conda install anaconda
```

Oh dear, that isn't what the person really wanted to do.

**Comment by chdoig** [comment]
>  "conda-env should only be in root env" (paraphrased): IMO, the same holds true for anaconda-client 

> I want to be able to do operations like "login" and "upload" and "download" with Anaconda Cloud from any environment. 

+100, @ijstokes! 

It really really annoys me, that I have to install anaconda-client in each of my environments. I see the ```error -bash: anaconda: command not found``` every time I try to upload anything. Also, because the commands are not consistent and the upload environment functionality is in conda env, but conda-env doesn't have anaconda-client as a dependency, the command always fails the first time you try it.

```bash
$ conda env upload ENVIRONMENT
Error: The anaconda-client cli must be installed to perform this action
```

**Comment by goanpeca** [comment]
I would add to what @ijstokes proposes that conda-tools in this case should also (eventually) contain the latest version of **Anaconda Client UI** (ex launcher)?

And also, although it is not meant to be launched from the command line, **Anaconda Client UI** (ex launcher) should be root installable only and accessible from any env.

**Comment by goanpeca** [comment]
Is this something that is still relevante @kalefranz ?

**Comment by kalefranz** [comment]
Nah I think the ideas here that are still relevant are captured in other issues.

**Comment by goanpeca** [comment]
Closing then!
