### ISSUE TITLE
Clean up test data organization

### ISSUE THREAD

**Issue by dsludwig** [Anaconda-Platform/anaconda-client#242]
Right now there are 7 data_dir/data_path method definitions:
- `binstar_client/`CLITestCase`defines`data_dir`method, locates all test files in`binstar_client/tests/data`
- `binstar_client/inspect_package/tests/*.py` each define a `data_path` function, relative to `__file__`
- `binstar_client/utils/notebook/tests/*.py` each define a `data_dir` method, relative to `__file__`

**Comment by goanpeca** [comment]
@dsludwig can you estimate some story points for this?
