### ISSUE TITLE
Improving Search: Show/filter by python version that package is built against.

### ISSUE THREAD

**Issue by naught101** [Anaconda-Platform/anaconda-client#281]
If I do something like `anaconda search <package>` then I get a nice table of all of the available packages on anaconda.org that are available for download. The table shows the repo name, the package version, package type, and platform, as well as comments. However, it's not possible to tell from this table whether the package will be installable, even if it's on the right platform, because it's likely to be built against a different version of python.

A couple of improvements would really help the search functionality:
- Show the versions of python and anything else relevant that the package is built against, e.g. `py34` or `np19py35`.
- Allow the results to be filtered by platform. When I'm on Linux, I don't care about Windows of OSX builds, and vice-versa
  - Also, allow filtering by python version (e.g. if the current env is using python 3.5, only show packages built against 3.5)
- Add a comment at the end of the table that describes how to install the package - e.g. "To install a package, use `conda install -c http://conda.anaconda.org/<repository> <package>`." (I know that I for one can never remember this URL - it's quite annoying). 

These little things would make using anaconda much more pain-free.

**Comment by stephenakearns** [comment]
Hi @naught101 these are all good suggestions. thanks for taking the time to mention them. We'll include them in our planning going forward.
