### ISSUE TITLE
Integration with AE-repo? (AS)

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Platform/anaconda-client#285]
For integration with the Enterprise Repo, can we remove everywhere it is hard-coded to use anaconda.org and have it check the .condarc (including the system one) for the default server to use? 

Also, we need an easy way for users to that grab miniconda/anaconda from their local  Repo server to have the defaults already setup. 

This should be pre-configured so 50 users don't all have to change their settings:

```
Site Config: /Library/Application Support/binstar/config.yaml
 + sites: {u'binstar': {u'url': u'https://api.anaconda.org'}, u'alpha': {u'url': u'http://api.alpha.binstar.org'}, 'wakari-as': {'url': 'http://54.208.244.133:8080/api'}}

User Config: /Users/bkreider/Library/Application Support/binstar/config.yaml
 + url: u'https://api.anaconda.org'
 + default_site: 'binstar'
 + sites: {u'binstar': {u'url': u'https://api.anaconda.org'}, u'alpha': {u'url': u'http://api.alpha.binstar.org'}, 'wakari-as': {'url': 'http://54.208.244.133:8080/api'}}
```

@mrduane @stephenakearns @srossross

**Comment by stephenakearns** [comment]
Hi @bkreider - wanting to understand the issue better here... 

when setting up enterprise customer client machines, we're expecting the following to occur: 
`anaconda config set url=subdomain.client.com`

after this command is run, any `conda install <package_name>` will default to the new URL.

**Comment by bkreider** [comment]
> after this command is run, any conda install <package_name> will default to the new URL.

That's only true for one user.  If i set an option in $PREFIX/.condarc it is set for all users, but the options set in anaconda client are only set for one user.  

It would be highly desired that the anaconda-client settings are stored in ~/.condarc and $PREFIX/.condarc.  

1.  This would reduce confusion for users.
2.  The config files would be more apparent rather than having to edit some weird hidden files that are hard to find.
3.  Global settings would already work.
4.  It makes it possible to have multiple anaconda client configs when doing things like testing.  Right now the config is tied to the user and not to the miniconda install.  conda lets you do both ways:  ~/.condarc works for all installed condas, $PREFIX/.condarc lets you have settings that are different per install.

**Comment by goanpeca** [comment]
Is this something still relevant with 5.x @bkreider, @kalefranz ?

**Comment by bkreider** [comment]
I think this has been fixed in anaconda-client.

**Comment by abarto** [comment]
This has been fixed.
