### ISSUE TITLE
Client should recognize AS API version

### ISSUE THREAD

**Issue by malev** [Anaconda-Platform/anaconda-client#289]
If one of our clients is using an older version of AS, `anaconda upload` might fail, for instance when uploading projects. We should be able to warn this to the user instead of showing an ugly error.

**Comment by stephenakearns** [comment]
Hi @malev - is this part of the PRs you are doing for upload or is it realted to the project execution project? (we should tag a milestone potentially)

**Comment by goanpeca** [comment]
Is this still relevant with 5.x @csoja @abarto?

**Comment by abarto** [comment]
@goanpeca I don't know.

**Comment by csoja** [comment]
At this point, I would say no.
