### ISSUE TITLE
Package hash/sign upload metadata?

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Platform/anaconda-client#310]
As part of verifying notebooks (and maybe other packages), it would be good to be able to provide some strong identity to the actual binary content that a user creates, before it goes over lots of pipes, filesystems, databases, etc. Additionally, being able to include a strong crypto signature of a package would be good for piece of mind, and in certain regulatory situations. 
### Approach

> Assuming #309, when a client uploads or downloads a package that they curate, the user has the option of applying the verification mechanisms, i.e. JSON validation. 

This would add an additional verification step for packages that elect to include a hash/signature when the data is as fresh as possible, namely immediately prior to upload. 

> Decision:
> - [ ] Once opted in by an upload, would verification trigger by default for a download client?

A verified upload would also include an immediate download... lots of bandwidth, though. The alternative it to perform independent verification on the server... lots of processing, though.

```
usage: anaconda upload [--hash HASH_CIPHER=sha256]
                       [--sign KEY]
                       [--verify ...] # see #309

optional arguments:
  --hash               calculate and store in metadata the crypto hash of the
                       published package. One of: <list of available>
  --sign               apply a GPG sign, using <list of available>
```

On the download side, we'd again need to have access to various approaches for doing verification, whether or not by default: locations of keystores, trusted servers, PKI, etc. Maybe something like [this](https://gist.github.com/lkdocs/6519372)

```
usage: anaconda download [--verify ...]
```

**Comment by stephenakearns** [comment]
@malev - can I get your thoughts on this one as someone who's worked a lot on upload functionality. 

@kalefranz - what is your thinking on support for signed conda packages?

Holding off on triaging until we've got a bit more discussion on this one.

**Comment by kalefranz** [comment]
I'm +10^6 on conda support for package signing. There's some beginning implementation already in the conda code base, but I think it started out wrong. It's using `pycrypto` right now. Should implement correctly from the beginning before people start using it with `TUF` and `cryptography`. Definitely in the conda backlog of things to do.

If someone wants to take on the project, would be happy to work with to get the implementation right.

**Comment by goanpeca** [comment]
@kalefranz is this something of relevance to keep track here, or is this tracked somewhere con conda (where I understand is where the work needs to be done)

**Comment by kalefranz** [comment]
I would close for now.
