### ISSUE TITLE
In `anaconda upload`, allow passing token and user as environment variables

### ISSUE THREAD

**Issue by pitrou** [Anaconda-Platform/anaconda-client#320]
This may make integration easier for third-party utilities such as `conda-build`, see https://github.com/conda/conda-build/issues/755

**Comment by stephenakearns** [comment]
These are good suggestions. Check to see if token is already possible (update docs if needed)

**Comment by j0hn** [comment]
You can set the token via env variable since `1.5.2`. You have to use `ANACONDA_API_TOKEN`. To specify other user you have to use that user's token.
