### ISSUE TITLE
DUPE: Anaconda upload noarch

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Platform/anaconda-client#323]
@kalefranz commented on [Fri May 06 2016](https://github.com/Anaconda-Platform/anaconda-server/issues/2144)

This issue is probably a dupe, but I wanted to file it so I can come back and track it down.  If it's a dupe, please link to relevant history and close.

The issue is that, with anaconda-build, the "upload to repo" portion--which uses anaconda-repo command line client--doesn't work for noarch packages.  The problem is that anaconda client isn't looking in the correct location.  This is possibly and upstream issue with conda or conda-build.  If so, please confirm and give details on what anaconda client needs.

https://anaconda.org/conda-team/pytest-cov/builds/10/0

**Comment by dsludwig** [comment]
There are issues for this in https://github.com/Anaconda-Platform/anaconda-build/issues/261 and https://github.com/conda/conda-build/issues/873.

Our proposed solution was to allow configuring where `conda-build` stores its output, so that we could know exactly where to upload from.

**Comment by stephenakearns** [comment]
closing this as duplicate - see the above 2 issues.
