### ISSUE TITLE
Port project upload to anaconda-project API

### ISSUE THREAD

**Issue by havocp** [Anaconda-Platform/anaconda-client#324]
See https://github.com/Anaconda-Platform/anaconda-project/pull/309 and https://github.com/Anaconda-Platform/anaconda-project/pull/306 for background.

Here is my strawman suggestion for what we should do:
 
 * remove utils/projects/models.py, filters.py, inspectors.py and optionally uploader.py
 * add an OPTIONAL dependency on anaconda-project, resolved at runtime. The problem is that anaconda-project also needs to depend on anaconda-client; so my suggestion is that for the conda packages, project requires client and not vice versa. If client needs project (for upload) and it isn't installed, it should give a runtime error message like "please install anaconda-project"
 * in the upload command, if is_project, check whether the anaconda_project module is available and give a nice error if not. If it is, use `anaconda_project.project_ops.upload` to upload the project.
 * To upload a plain .py file, make a temp directory, use `project_ops.create(name=basename_without_extension)` and then use `project_ops.upload` to upload it.

If we keep `uploader.py` here, then it should be updated from the `anaconda_project/client.py` I have now in anaconda-project, which will need to be refactored so it doesn't depend on the `Project` object perhaps. Then I'd import and use the uploader from anaconda-project, but I guess anaconda-client would not use it directly itself. But it also works fine I think to leave client.py over in `anaconda_project`.

**Comment by stephenakearns** [comment]
Hi @havocp and @malev - I think this is already done - the attached PR is merged. I'm closing it, but if that's not correct, please reopen and outline next steps?

**Comment by havocp** [comment]
The anaconda-project part is done but not the anaconda-client part.

**Comment by havocp** [comment]
(The user-visible importance of this one is that "anaconda upload" won't upload projects correctly without this work.)

**Comment by havocp** [comment]
We need to decide what to do with the `--summary` and `--description` options for projects. Description is redundant with the description field in `project.yml` and I don't know how summary differs from description.
