### ISSUE TITLE
Color changing after an error

### ISSUE THREAD

**Issue by ilanschnell** [Anaconda-Platform/anaconda-client#326]
@SHAPESNATCH opened this issue https://github.com/ContinuumIO/anaconda-issues/issues/808

**Comment by goanpeca** [comment]
Has this been reproduced @abarto, @j0hn ? seems like a windows (old) issue. Just want to check if this is relevant ;-)

**Comment by abarto** [comment]
This is no longer valid as we removed clyent's coloring (we're trying to remove clyent).
