### ISSUE TITLE
`conda install` generates spurious warning

### ISSUE THREAD

**Issue by stefanseefeld** [Anaconda-Platform/anaconda-client#330]
Running
`conda install mkl`

I get this warning

```
Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/t/<TOKEN>/accelerate/linux-64/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/...<token redacted>.../accelerate/linux-64/repodata.json.bz2)Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/t/<TOKEN>/accelerate/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/...<token redated>.../accelerate/noarch/repodata.json.bz2)
```

which seems wrong, as the express reason for using an authentication token is to avoid having to log in. (This is particularly annoying when running in non-interactive environments such as on CI platforms.)

**Comment by kalefranz** [comment]
@stefanseefeld Is there a CI link or something you can reference here to show me more output?  Basically more information of the environment setup.

**Comment by MulticastMatt** [comment]
Hi @kalefranz - could you please create this in the Conda repo as this is a conda issue.  I'm going to close this in the Anaconda Client repo.  Thanks @stefanseefeld for reporting.
