### ISSUE TITLE
anaconda download generates an error for notebook files

### ISSUE THREAD

**Issue by ltransom** [Anaconda-Platform/anaconda-client#336]
The following error is produced when downloading a non Notebook file using `anaconda download`:

`[ERROR]
Traceback (most recent call last):
  File "/Users/lransom/anaconda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/Users/lransom/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/Users/lransom/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/Users/lransom/anaconda/lib/python2.7/site-packages/binstar_client/commands/download.py", line 64, in main
    log.info(err.msg)
AttributeError: 'BinstarError' object has no attribute 'msg'`

The file is actually downloaded successfully.  The error happens after the download completes as the call to `has_envrionment` assumes the file is a Notebook and throws an exception if the file is not JSON.

https://github.com/Anaconda-Platform/anaconda-client/blob/359aa18cd7ab40c67a2604fbda491d1fe5637f11/binstar_client/utils/notebook/__init__.py#L44

**Comment by sandhujasmine** [comment]
A client would like to upload a zip file to their internal repo. I'm able to upload the zipfile using anaconda-client. This is being done from AEN so it is anaconda-client version 1.4.0

Download raises above exception. Uploading other types of files to an internal repo is part of the [enterprise default functionality](https://docs.continuum.io/anaconda-cloud/using#uploading-other-types-of-files).

**Comment by bkreider** [comment]
I'm increasing the severity since it blocks a feature with no known workaround.

**Comment by DavidMertz** [comment]
Fixing this will provide a workable solution for Cisco's need to clone environments.  It's still a bit hodge-podge and a general "Clone Project" button would be much better.  But they'll be happy with it for now.
