### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/anaconda-client#340]
Having a little trouble determining the license ATM. Is this BSD 3-Clause per usual or is it something else?

**Comment by jakirkham** [comment]
Could someone please clarify the license? I'm hoping this is an easy question. 😄

**Comment by srossross** [comment]
> Could someone please clarify the license?

Yes, this should be a BSD 3-Clause license. We will update this in the next release.

**Comment by jakirkham** [comment]
Thanks for clarifying, @srossross.
