### ISSUE TITLE
miniconda requires anaconda-client to avoid "somethings is wrong" error

### ISSUE THREAD

**Issue by rwarren** [Anaconda-Platform/anaconda-client#343]
Not sure this is the correct location to file this bug, but I can't find the pure conda repo.

I have a recent miniconda install and am running the latest conda (4.1.9).  Any conda commands were always displaying a cryptic message prior to the expected output.  For example:

```
$ conda info --envs    
Warning: somethings is wrong with binstar_client (No module named 'binstar_client')# conda environments:
#
<snip>
```

Digging into it I see that binstar was the old name for the anaconda cloud.  Installing the anaconda-client fixes the problem (even though I don't want/need it):

```
$ conda install anaconda-client
Fetching package metadata .......
<snip>
$ conda info --envs
# conda environments:
#
<snip>
```

**Comment by goanpeca** [comment]
I think this issue is no longer relevant
