### ISSUE TITLE
Handle ctrl-c

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Platform/anaconda-client#357]
Handle ctrl-c when exiting when a airgap customer is trying to login to anaconda.org.  It should also capture if it times out here because of the firewall.

**Comment by goanpeca** [comment]
@bkreider is this still relevant?

**Comment by bkreider** [comment]
It depends if anaconda-client handles ctrl-c now.  I haven't tested it in a while.

**Comment by abarto** [comment]
Right now anaconda-client reacts to ctrl-c, but it just quits without logging.
