### ISSUE TITLE
Anaconda upload broken in interactive mode when package exists and is not overwritten

### ISSUE THREAD

**Issue by rolando** [Anaconda-Platform/anaconda-client#364]
Sorry for the lack of traceback but this happened in our build system.

I tracked down the issue to the `upload_package` function: https://github.com/Anaconda-Platform/anaconda-client/blob/develop/binstar_client/commands/upload.py#L163

which may return `[]`: https://github.com/Anaconda-Platform/anaconda-client/blob/develop/binstar_client/commands/upload.py#L193

and that value is appended to a list: https://github.com/Anaconda-Platform/anaconda-client/blob/develop/binstar_client/commands/upload.py#L241

And then the `main` function attempts to iterate `[[]]` as a list of tuples: https://github.com/Anaconda-Platform/anaconda-client/blob/develop/binstar_client/commands/upload.py#L248

raising the exception `ValueError: need more than 0 values to unpack`

**Comment by dsludwig** [comment]
Thanks for the report, @rolando!

This is fixed in the latest release of anaconda-client (1.5.2). You can update to the latest version by:

```
conda update anaconda-client
```

**Comment by rolando** [comment]
👍
