### ISSUE TITLE
Problem installing music21

### ISSUE THREAD

**Issue by thompsda88** [Anaconda-Platform/anaconda-client#378]
I attempted to download music21 3.0.3alpha on Mac OS X El Capitan 10.11.5. I used the following command:

conda install -c maxalbert music21=3.0.3alpha

This is what resulted:

PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels: 
  - music21 3.0.3alpha*

Any help would be appreciated. Thanks.
DT

**Comment by goanpeca** [comment]
Hi @thompsda88, as the error points out:

**Package missing in current osx-64 channels:**

If you go to https://anaconda.org/maxalbert/music21/files?version=3.0.3alpha

You will see that for that version only Linux packages are available (not osx, not windows). In fact for any version of that package I only see Linux packages.

<img width="1115" alt="screen shot 2016-12-07 at 6 52 02 am" src="https://cloud.githubusercontent.com/assets/3627835/20966722/b50d3772-bc49-11e6-83eb-6d1d6a86db8f.png">
