### ISSUE TITLE
Do not exact package attributes from recipe.json file.

### ISSUE THREAD

**Issue by jjhelmus** [Anaconda-Platform/anaconda-client#379]
`anaconda-client` [uses the contents of the `recipe.json` file](https://github.com/Anaconda-Platform/anaconda-client/blob/develop/binstar_client/inspect_package/conda.py#L89-L93) to extract the package attributes (summary, license and homepage) when the package is uploaded to Anaconda.org.  

This file is no longer included by package created by `conda-build`, (conda/conda-build#781).

When uploaded, packages which are missing a `recipe.json` file will have default values used for this metadata ("No Summary", "Unspecified") unless manually specified by the user.  For example, https://anaconda.org/conda-forge/fenics.

Either this file should be added back to packages created by `conda-build` or `anaconda-client` should be updated to extract this metadata from the `about.json` file.  The later makes more sense to me.  

I opened a similar issue, conda/conda-build#1577 in `conda-build` so that both projects can track this problem.

**Comment by msarahan** [comment]
The information in this file has been split into a rendered version of the input recipe, and a json file, ``about.json`` that contains this metadata.  It should be sufficient to look for about.json, and fall back to the older recipe.json if it is not found.

Example about.json contents:

```
{
  "channels": [
    "https://repo.continuum.io/pkgs/free/osx-64",
    "https://repo.continuum.io/pkgs/free/noarch",
    "https://repo.continuum.io/pkgs/pro/osx-64",
    "https://repo.continuum.io/pkgs/pro/noarch",
    "https://conda.anaconda.org/r/osx-64",
    "https://conda.anaconda.org/r/noarch"
  ],
  "conda_build_version": "2.0.12+7.g7402bf7.dirty",
  "conda_env_version": "4.2.4.dev378+3484810",
  "conda_private": false,
  "conda_version": "4.2.4.dev378+3484810",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "CONDA_DEFAULT_ENV": "<not set>",
    "CONDA_ENVS_PATH": "<not set>",
    "DYLD_LIBRARY_PATH": "<not set>",
    "PATH": "/Users/msarahan/miniconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Library/TeX/texbin",
    "PYTHONHOME": "<not set>",
    "PYTHONPATH": "<not set>"
  },
  "home": "https://github.com/conda/conda-build",
  "license": "BSD 3-clause",
  "offline": false,
  "root_pkgs": [
    "anaconda-client-1.6.0-py27_0"
  ]
}
```
