### ISSUE TITLE
anaconda upload stuck at 100%

### ISSUE THREAD

**Issue by looooo** [Anaconda-Platform/anaconda-client#384]
anaconda upload of a specific package stuck at 100%. On the anaconda website there is an information about a package uploaded but no package is available.

I already asked here:
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/aTAbbprqv30

I tried to remove this package completely (there were some uploads available previously), but I had still no success. Maybe someone can have a look at this.

**Comment by looooo** [comment]
after resetting the build number to 0 (previously it was 11) the upload worked. No idea what was wrong. I leave this issue open.

**Comment by looooo** [comment]
Now I have tried to rename my package. And again the upload wasn't successfully.

![grafik](https://cloud.githubusercontent.com/assets/5084704/22584621/aa22302e-e9f3-11e6-9235-5c94309d5206.png)

There seems to be enough space. But I have often removed packages. Maybe this could be the problem?

**Comment by j0hn** [comment]
@looooo i'm trying to fix this issue but i can't reproduce the error. Any chance you can send me the package that you're trying to upload so i can see what's wrong with it?

**Comment by looooo** [comment]
I can send you the package, but I have the feeling it's not a problem of the package. The problem also occurs with other packages... As I said this is maybe related to the anaconda cloud service.

**Comment by looooo** [comment]
After testing the upload again (other machine) the package was successfully uploaded. https://anaconda.org/freecad/freecad/files Quite strange... I think we can temporary close the issue :-)

**Comment by looooo** [comment]
just had the issue again. Maybe this is related to uploading from virtual machine.... No idea.
