### ISSUE TITLE
No error when trying to upload nonexistent file

### ISSUE THREAD

**Issue by mausch** [Anaconda-Platform/anaconda-client#391]
anaconda-client 1.6.2 on Python 3.5

Running `anaconda upload kjasndfkjansdlfjansd` (i.e. a nonexistent package) only displays:
`Using Anaconda API: https://api.anaconda.org`

It should display something like "Could not find package to upload 'kjasndfkjansdlfjansd'".

At least it does return a non-zero exit code :)

**Comment by stephenakearns** [comment]
Just lost 10 min of my life I'm not getting back on this one.. ;-)

**Comment by j0hn** [comment]
Couldn't reproduce on `anaconda client 1.6.5`

```bash
$ anaconda upload asdjkasd
Using Anaconda API: https://api.anaconda.org
[ERROR] file asdjkasd does not exist
```
