### ISSUE TITLE
when write conda or pip in console it launch python ,instead of doing the actual conda command ?

### ISSUE THREAD

**Issue by abdolrhman** [Anaconda-Platform/anaconda-client#396]
Hello guys , i have a huge problem , 
now i installed anacodna , every thing work fine , ok ..
then i restart my pc , open my console , write conda to give me conda commands , instead it launched a python console?!!!!
i tried to use pip instead , same give me python instead of the actual commands , so its like pip and conda are useless , they doesn't do any thing except give me python console !!??
i re installed Anaconda , same , worked first fine , then restarted my pc , Bomb again python console .

Please Help me , i search every thing lots of days , i found nothing , if any thing know any thing , please tell me , am really tired of all of this ! 

thanks in advance
http://imgur.com/a/lwiQC

**Comment by goanpeca** [comment]
If you are still experiencing the problem please open it at https://github.com/ContinuumIO/anaconda-issues/issues
