### ISSUE TITLE
The -s option is gone in version 1.6.2

### ISSUE THREAD

**Issue by joelhullcio** [Anaconda-Platform/anaconda-client#400]
anaconda upload use to have a -s option to specify the upload site.
In version 1.6.2 this option is gone.

This is a problem and a regression of functionality.  The -s option is very useful for enterprises that support multiple sites.  **Please add it back in ASAP.**

Also, there is no error or warning when the -s is specified.  Instead the files are just uploaded to the default site in the anaconda config.

**Comment by j0hn** [comment]
@joelhullcio The option is still there, it's not an option of the upload command but an option of the anaconda command itself. So you have to do:

```bash
$ anaconda -s your_site upload whatever
```

**Comment by joelhullcio** [comment]
Thanks, I missed that somehow.
