### ISSUE TITLE
PEP440 and local version identifiers

### ISSUE THREAD

**Issue by tonigi** [Anaconda-Platform/anaconda-client#401]
I've got packages with local version identifiers, but the conda install command may not handle version precedence according to PEP440. In particular

    >>> from packaging.version import Version, parse
    >>> parse("2.3.0+htmd4") > parse("2.3.0")
    True  # This follows PEP440

while conda install prefers version 2.3.0 to 2.3.0+htmd4.

**Comment by goanpeca** [comment]
@tonigi I think you got the wrong repository. Try either

https://github.com/ContinuumIO/anaconda-issues/issues

or directly on the conda repo

https://github.com/conda/conda/issues
