### ISSUE TITLE
Central location for client configuration

### ISSUE THREAD

**Issue by hsparra** [Anaconda-Platform/anaconda-client#412]
For centralized installations on Linux, it'd be helpful if the configuration file for the anaconda client (config.yaml) is handled the same way as the configuration file for conda (.condarc).

Currently, users can have a personal configuration in their home directory (~/.config/binstar/config.yaml), and this is consistent with how users can have a personal ~/.condarc file. However, the system config.yaml file is stored in /etc/xdg, which cannot easily be shared across Linux servers. It'd be helpful if the system config.yaml file could be located on a central NAS location, like is possible for the system .condarc file.

**Comment by bkreider** [comment]
I'm closing this as stale.  The system config file is no longer located at /etc/xdg, but is relative to the conda environment with which it is installed.
