### ISSUE TITLE
anaconda-client fails silently on bad SSL

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Platform/anaconda-client#419]
`anaconda login` silently fails when the SSL certificate fails validation.  It looks like the URL is bad, or the server is down, but it's actually caused by certificate validation.

**Comment by brendancol** [comment]
@bkreider I'm currently experiencing this issue on a client deployment.  I've tried setting `ssl_verify: false` and `verify_ssl:false`, but still cannot connect.  Any ideas on how to make a anaconda-client work with an bad SSL certificate?

**Comment by brendancol** [comment]
This was user error.  Just to review. The steps I needed were:

```bash
conda config --set ssl_verify False
anaconda config --set verify_ssl false
```

**Comment by brendancol** [comment]
This issue can be closed
