### ISSUE TITLE
Client can't access shared environment on anaconda

### ISSUE THREAD

**Issue by szha** [Anaconda-Platform/anaconda-client#432]
when running `conda env update mxnet/gluon`, anaconda-client complains about not being able to access binstar prod s3 bucket.
https://discuss.gluon.ai/uploads/default/original/1X/c40c1cad836e7a94b94fd375f60a4dc0f2397667.png

**Comment by goanpeca** [comment]
This should probably go to conda issue tracker

**Comment by szha** [comment]
@goanpeca where is such tracker?

**Comment by goanpeca** [comment]
https://github.com/conda/conda/issues, but feel free to reopen as needed!
