### ISSUE TITLE
Python has stopped working

### ISSUE THREAD

**Issue by 03vikas** [Anaconda-Platform/anaconda-client#447]
python has stopped working while opening jupyter notebook in windows 7 ultimate.
How to solve this problem. 
Jupyter notebook get opened but when trying to open Python file or any file then it shows message "**Python stopped working**" and after closing that another message prompted "**creating Notebook failed**".
Please let me know if anyone has corrected this problem.
![snapshot](https://user-images.githubusercontent.com/34694308/34205471-8f99b78e-e5a8-11e7-9118-22fc384d0d08.png)

**Comment by goanpeca** [comment]
If you are still experiencing this issue please open it at 
https://github.com/ContinuumIO/anaconda-issues/issues

And provide all the requested information

**Comment by goanpeca** [comment]
Please report this over https://github.com/ContinuumIO/anaconda-issues/issues
