### ISSUE TITLE
Anaconda Repo Upload trouble with 1.6.6

### ISSUE THREAD

**Issue by brendancol** [Anaconda-Platform/anaconda-client#450]
After upgrading anaconda-client to `1.6.6` and using `verify_ssl = False`, I ran into trouble while uploading packages to an Anaconda Repo instance at a client site (AE4).  Basically it looks like the package is uploaded, but it never displays the `Upload Complete` message on the terminal.

In the anaconda-repo GUI, it says the package was uploaded, but then clicking on the link leads to a 403 / not authorized screen.

We downgraded anaconda-client to `1.6.5` and all worked as expected.

**Comment by goanpeca** [comment]
@abarto @j0hn this is related to the deprecation of verify_ssl to ssl_verify?

**Comment by abarto** [comment]
@goanpeca It wasn't deprecated. I'm looking into this right now.

**Comment by abarto** [comment]
@brendancol which version of Repo are you using?

**Comment by goanpeca** [comment]
>@goanpeca It wasn't deprecated. I'm looking into this right now.

Yes it was, [deprecated](https://github.com/Anaconda-Platform/anaconda-client/blob/d6d9b77b9ef0cc924b70474148ca5d8ae7468909/binstar_client/commands/config.py#L78).

**Comment by abarto** [comment]
Sorry, I meant to say it wasn't removed.

**Comment by goanpeca** [comment]
@abarto was this fixed?

**Comment by abarto** [comment]
This was fixed.
