### ISSUE TITLE
Uploading packages to another user's channel

### ISSUE THREAD

**Issue by gbrener** [Anaconda-Platform/anaconda-client#456]
Hi team, as a user of anaconda.org with package-upload privileges to a channel I do not own, is there a recommended way to upload a package to the channel?

I tried the following things, which did not work:
- Added `-u` option on command-line
- Created token on anaconda.org with upload privileges, added with `-t` option on command-line
- Both of the above at once

One thing that did work:
- Asked the channel owner to provide a token that they created, and passed it with `-t` (and no `-u` flag)

I wonder if this is an expected behavior / limitation, or if there is something I have missed.

**Comment by abarto** [comment]
That's expected behavior. The -u is used when you want to upload to an organization you're part of.

**Comment by goanpeca** [comment]
@abarto are you sure?

The CLI does say

```
anaconda upload --help
...
optional arguments:
...
  -u USER, --user USER  User account or Organization, defaults to the current
                        user
...
```

**Comment by abarto** [comment]
If a user shares his or her token, you can indeed upload to the account associated with it.

**Comment by goanpeca** [comment]
Asked the channel owner to provide a token that they created, and passed it with -t
