### ISSUE TITLE
Anaconda prompt not recognized

### ISSUE THREAD

**Issue by tymer5** [Anaconda-Platform/anaconda-client#461]
I am first time user. I purchased a course on programming in python. The course highly suggested downloading anaconda for ease of installation. I have installed on windows 64 bit machine. After install it says to go to command prompt and type jupyter notebook. I get the error 

'jupyter' is not recognized as an internal or external command, operable program or batch file.

I have searched google and found that I should run anaconda from the start menu. Under a folder anaconda3 (64 Bit) I have one file to select which is Anaconda Prompt. When I select that I get a command window and the following message.

activate.bat' is not recognized as an internal or external command,
operable program or batch file.

Google search says I need to add the path to activate.bat I did a search on my computer for the file and found three files by that name all within the anaconda3 folder and sub-folders. None of these were in the anaconda3\scripts folder as expected from the google articles.
C:\Users\Ty\Anaconda3\pkgs\conda-4.4.10-py36_0\Scripts
C:\Users\Ty\Anaconda3\Lib\venv\scripts\nt
C:\Users\Ty\Anaconda3\pkgs\python-3.6.4-h6538335_1\Lib\venv\scripts\nt

I tried adding C:\Users\Ty\Anaconda3\pkgs\conda-4.4.10-py36_0\Scripts to my path but got the same message. 

I typed in where activate.bat and it gave me the location I just added to the path. 

I typed activate at the command prompt and got the following message.
Unable to create process using 'C:\Users\Ty\Anaconda3\pkgs\conda-4.4.10-py36_0\python.exe C:\Users\Ty\Anaconda3\pkgs\conda-4.4.10-py36_0\Scripts\conda-script.py shell.cmd.exe activate activate'

I am not sure where to go from here. 

Please help.

**Comment by mingwandroid** [comment]
It sounds like your installation did not complete successfully.

Do you have any other Python interpreters installed? Perhaps a virus scanner got in the way of the install process, you could try disabling it temporarily if so.

**Comment by tymer5** [comment]
Hi mingwandroid. Thank you for responding. I have uninstalled and re-installed several times now. This time I have taken some pictures of the completed installation and last lines run from the details of the installer. I am at a loss of what to do. I have completely disabled my firewall and windows defender software for this install. On finishing I went to the command prompt and typed in jupyter notebook and got the same error. I restarted the computer and I added the location to my directory and it will recognize now jupyter but not notebook. here is a copy of my command screen. I also tried the anaconda prompt and got the same error as above. Again the activate.bat file is not in the scripts directory but it is in the three other directories as above. 

Any help you can give?

Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Ty>jupyter notebook
Error executing Jupyter command 'notebook': [Errno 'jupyter-notebook' not found] 2

C:\Users\Ty>jupyter notebook
Error executing Jupyter command 'notebook': [Errno 'jupyter-notebook' not found] 2

C:\Users\Ty>jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required

C:\Users\Ty>

This is the first time I am installing Python so I don't believe I have any other interpreters installed. On the last installs I was  unable to install the Microsoft VSCode. It asked me to be sure I was connected to the internet. I was. Retry did not work. So this time when I installed I skipped installing the Microsoft VSCode. Here are some pictures of the final windows of the installer. They appear to not have any errors and look as though it has installed correctly. 
![install complete 1](https://user-images.githubusercontent.com/36675994/36469594-952d2b3e-169c-11e8-8f6f-aa831aba56e9.PNG)
![install complete 2](https://user-images.githubusercontent.com/36675994/36469595-95425108-169c-11e8-91e1-3457aa151414.PNG)
![install complete 3](https://user-images.githubusercontent.com/36675994/36469597-95565270-169c-11e8-89bb-436268e60324.PNG)
![install complete 4](https://user-images.githubusercontent.com/36675994/36469598-95692e0e-169c-11e8-9f22-e9126f0b3ff8.PNG)

**Comment by mingwandroid** [comment]
This is really strange then. I am a little bit at a loss to figure out what's up here.

Can you try uninstalling then installing the latest Miniconda instead and seeing if the Anaconda Prompt works?

**Comment by tymer5** [comment]
Where do I get miniconda? Can you provide a link to miniconda download? I only see anaconda downloads.

**Comment by tymer5** [comment]
Never mind I found miniconda it. I will let you know how it goes. Here is the link to where I found it.
https://conda.io/miniconda.html

**Comment by tymer5** [comment]
I think that worked but since I am new to this I don't know where to go with it from here. The jupyter notebook command still doesn't work. I am assuming it wasn't installed with the mini. I did a search for jupyter in the miniconda3 file structure that came up empty. Here are some screen shots of what I have at this point.
![install complete 5](https://user-images.githubusercontent.com/36675994/36508346-548fcec2-1711-11e8-81cc-dde1d51a7772.PNG)
![install complete 6](https://user-images.githubusercontent.com/36675994/36508347-54c2b2a6-1711-11e8-9a09-7ccdbce2fb83.PNG)
![install complete 7](https://user-images.githubusercontent.com/36675994/36508348-54e145c2-1711-11e8-82bc-0f53355110cc.PNG)

**Comment by mingwandroid** [comment]
Now run `conda install anaconda`

**Comment by tymer5** [comment]
Well that looked like it was working, but when it got to the end it had some problems executing something. Here are some screenshots. 
![install complete 8](https://user-images.githubusercontent.com/36675994/36510484-00f5963c-1718-11e8-8d07-898c7f13a9e8.PNG)
![install complete 9](https://user-images.githubusercontent.com/36675994/36510485-01112a00-1718-11e8-8b63-a4c532c8021a.PNG)

**Comment by tymer5** [comment]
I tried running the command again with the v option as described. I don't know if i did it right or not. I'm not sure if I was supposed to uninstall or not. I did not. I just ran it. Below is a screenshot of what happened. Please let me know if I should have done something else or if you have any ideas for me to try.
![install complete 10](https://user-images.githubusercontent.com/36675994/36523098-d74c5090-1754-11e8-8992-f9b7690a8d7c.PNG)

**Comment by tymer5** [comment]
Any thoughts or comments on what I can do?

**Comment by tymer5** [comment]
Juanpa has educated me a bit over on stackoverflow, and shown me that I wan't running the verbose mode properly. Below is a cleaner explanation of the problem.

I am having difficulty installing Anaconda and getting Jupyter to install/launch. I downloaded the installation package for Windows 64 Bit Graphical Installer from https://www.anaconda.com/download/

I turned off windows defender software.

I ran the installation program following all recommendations and it appeared to install properly without throwing any errors.

I opened a cmd window and tried to run Juypter it was not recognized.

I tried to run Anaconda it was not recognized.

I searched the internet and read suggestions to add the location to my path. And found the Activate.bat file was not in the scripts folder as it was expected to be.

I installed miniconda and then used that to try to install anaconda.

It warned to update the conda program first. I did then tried to install anaconda. It got to Executing transaction and then failed. I have tried to uninstall and install multiple times. It always seems to fail at the same place. I am at a loss of what to try next. Can someone with knowledge look at the verbose information and please give advise, or point me to a solution.

Thanks in advance.

>Preparing transaction: ...working... done
>Verifying transaction: ...working... done
>Executing transaction: ...working... ===> LINKING PACKAGE: defaults::icc_rt-2017.0.4-h97af966_0 <===
> prefix=C:\Users\Ty\Miniconda3
>source=C:\Users\Ty\Miniconda3\pkgs\icc_rt-2017.0.4-h97af966_0


>===> LINKING PACKAGE: defaults::intel-openmp-2018.0.0-hd92c6cd_8 <===
 > prefix=C:\Users\Ty\Miniconda3
  >source=C:\Users\Ty\Miniconda3\pkgs\intel-openmp-2018.0.0-hd92c6cd_8

It proceeds to link many packages which appear normal so I have not included here other than the first and last. Then it changes at a cmd.exe. It fails and begins rolling back and reversing packages. The results follow. In these results at the bottom it begins a long list of reversing packages that look normal before it gives a done message and provides Traceback.

>===> LINKING PACKAGE: defaults::ipykernel-4.8.0-py36_0 <===
 > prefix=C:\Users\Ty\Miniconda3
>  source=C:\Users\Ty\Miniconda3\pkgs\ipykernel-4.8.0-py36_0


>$ C:\WINDOWS\system32\cmd.exe /d /c C:\Users\Ty\Miniconda3\Scripts\.ipykernel-post-link.bat
>==> cwd: C:\Users\Ty\Miniconda3\Scripts <==
>==> exit code: 1 <==
>==> stdout <==
>b''
>==> stderr <==
>b''


>===> REVERSING PACKAGE LINK: defaults::ipykernel-4.8.0-py36_0 <===
>  prefix=C:\Users\Ty\Miniconda3


>failed
>An error occurred while installing package 'defaults::ipykernel-4.8.0-py36_0'.
>LinkError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
>running your command again with `-v` will provide additional information
>location of failed script: C:\Users\Ty\Miniconda3\Scripts\.ipykernel-post-link.bat
>==> script messages <==
><None>

>Attempting to roll back.
>
>
>Rolling back transaction: ...working... ===> REVERSING PACKAGE LINK: defaults::seaborn-0.8.1->py36h9b69545_0 <===
>  prefix=C:\Users\Ty\Miniconda3


>===> REVERSING PACKAGE LINK: defaults::nbconvert-5.3.1-py36h8dc0fde_0 <===
>  prefix=C:\Users\Ty\Miniconda3

Below is the Traceback.

>===> REVERSING PACKAGE LINK: defaults::icc_rt-2017.0.4-h97af966_0 <===
>  prefix=C:\Users\Ty\Miniconda3


>done
>Traceback (most recent call last):
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\core\link.py", line 770, in run_script
>    subprocess_call(command_args, env=env, path=dirname(path))
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\gateways\subprocess.py", line 56, in >subprocess_call
>    output=_format_output(command_str, path, rc, stdout, stderr))
>subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\cmd.exe', '/d', '/c', >'C:\\Users\\Ty\\Miniconda3\\Scripts\\.ipykernel-post-link.bat']' returned non-zero exit status 1.

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\core\link.py", line 537, in _execute_actions
>    run_script(target_prefix, prec, 'post-unlink' if is_unlink else 'post-link')
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\core\link.py", line 786, in run_script
>    raise LinkError(message)
>conda.exceptions.LinkError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
>running your command again with `-v` will provide additional information
>location of failed script: C:\Users\Ty\Miniconda3\Scripts\.ipykernel-post-link.bat
>==> script messages <==
><None>


>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\core\link.py", line 472, in _execute
>    cls._execute_actions(pkg_idx, axngroup)
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\core\link.py", line 553, in _execute_actions
>    reverse_excs,
>conda.CondaMultiError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
>running your command again with `-v` will provide additional information
>location of failed script: C:\Users\Ty\Miniconda3\Scripts\.ipykernel-post-link.bat
>==> script messages <==
><None>



>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\exceptions.py", line 789, in __call__
>    return func(*args, **kwargs)
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
>    exit_code = do_call(args, p)
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
>    exit_code = getattr(module, func_name)(args, parser)
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 11, in execute
>    install(args, parser, 'install')
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\cli\install.py", line 255, in install
>    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\cli\install.py", line 285, in handle_txn
>    unlink_link_transaction.execute()
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\core\link.py", line 225, in execute
>    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
>  File "C:\Users\Ty\Miniconda3\lib\site-packages\conda\core\link.py", line 500, in _execute
>    rollback_excs,
>conda.CondaMultiError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
>running your command again with `-v` will provide additional information
>location of failed script: C:\Users\Ty\Miniconda3\Scripts\.ipykernel-post-link.bat
>==> script messages <==
><None>




(base) C:\Users\Ty> 

Again Thanks in advance for your help.

**Comment by tymer5** [comment]
I see this was closed but it has not been answered or resolved. I am still unable to install anaconda. Is there a reason why the problem I am having is tagged as invalid? What makes it invalid? Please explain or help by pointing me in the right direction.

**Comment by samv1993** [comment]
I have the same problem, I cleaned all the python versions and closed any other programs. It does not work.

**Comment by tymer5** [comment]
The first error is 

C:\Users\Ty\Miniconda3\Scripts.ipykernel-post-link.bat

When I go to directory C:\Users\Ty\Miniconda3\Scripts

I can not find the file ipykernel-post-link.bat

When I search for that file I find it under

C:\Users\Ty\Miniconda3\pkgs\ipkernel-4.8.0-py36_0\scripts

So is this because it is given the wrong location to look for that file or because it was unpacked after it ran into the error? Should I copy that file to the C:\Users\Ty\Miniconda3\Scripts folder and then give it another try?
I down loaded the Geany editor so I could take a look inside some of these files. Here is what is in the ipykernel-post-link.bat file in case someone can interpret it. I can not.

@echo off

:: Install kernelspec at post-link because conda doesn't substitute Windows paths correctly in JSON files
"%PREFIX%\python.exe" -m ipykernel install --sys-prefix > NUL 2>&1 && if errorlevel 1 exit 1

Please advise....

**Comment by tymer5** [comment]
Reading the contents of the ipykernel-post-link.bat file, I see that the end of the last file says "if errorlevel 1 exit 1" When the install program tries to find this file and run it but then fails the next lines say.

$ C:\WINDOWS\system32\cmd.exe /d /c C:\Users\Ty\Miniconda3\Scripts.ipykernel-post-link.bat
==> cwd: C:\Users\Ty\Miniconda3\Scripts <==
==> exit code: 1 <==
==> stdout <==
b''
==> stderr <==
b''

===> REVERSING PACKAGE LINK: defaults::ipykernel-4.8.0-py36_0 <===
prefix=C:\Users\Ty\Miniconda3

so I assume it finds the file and executes it's line of code. Any experts out there who can comment?

**Comment by samv1993** [comment]
I cannot waste my time on finding the bug. I just reinstalled Windows OS, and it now works. Many people have the same problems on the install. I hope they can find out what happened quickly.

**Comment by goanpeca** [comment]
@kalefranz thoughts?

**Comment by goanpeca** [comment]
Please open over https://github.com/ContinuumIO/anaconda-issues/issues if the problem continues.

This repository is for anaconda-client, the CLI for communicating with anaconda.org

**Comment by FathiahHusna** [comment]
try read through this website. it is the official troubleshooting from anaconda documentation. perhaps your error has the solution(s) in here. 
https://docs.anaconda.com/anaconda/user-guide/troubleshooting#anaconda-installer-download-problems

**Comment by icereal** [comment]
I solved the problem by uninstalling minconda3 from Windows 10 Apps and Features, rebooted the computer and tried installing a new package _conda install <package name>_

**Comment by DavidSmolinski** [comment]
When I was learning python, Anaconda cost me a lot of time. Learning to install Pycharm took 3x as long as learning basic python. The important part was deleting Anaconda from the path. 

Now I have to learn Jupyter notebooks. They recommended Anaconda. I installed it and did not add it to the path. I opened Command Prompt and typed "conda install -c conda-forge jupyterlab". 
output message: 'conda' is not recognized as an internal or external command,
operable program or batch file.

I'm using Windows 7.

**Comment by msarahan** [comment]
You need to use Anaconda Prompt.  That takes care of modifying PATH for you in a clean, local way.  If you'd rather that conda be more globally available, you can run ``conda init`` from an Anaconda Prompt, and it will make conda available in future plain cmd.exe sessions.

**Comment by xinyangubc** [comment]
activate env.(yourname)
and then do:
conda install nb_conda

**Comment by fiza09** [comment]
I ran into this issue in pycharm. What also works is physically adding your path to anaconda in your PATH variable in advanced system settings under settings in Windows 10 (after global installation).

**Comment by AmitSharma1127** [comment]
Works after using 'conda init'

**Comment by AmitSharma1127** [comment]
Works after using `conda init`

The powershell needs to be first initiated to be used for conda CLI to work correctly

**Comment by aktaraydin** [comment]
I spent two days to solve this problem. I tried all "path" proposals. Finally I found this path under "System Variables/path": 

search-ms:displayname=Search%20Results%20in%20Anaconda3_64&crumb=location:D%3A%5CProgram%20Data%5CAnaconda3_64\pyinstaller-3.6-py37h62dcd97_5

When I delete this, problem has been solved. I want to add this solution in here maybe it might be solution to someone
