### ISSUE TITLE
get_binstar function missing in 1.6.11

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/anaconda-client#463]
We ran into an issue with `anaconda-client` 1.6.11 where it appears `get_binstar` is no longer available. Had been using 1.6.5 recently. This affects conda-forge uploads.

```
anaconda_upload is not set.  Not uploading wheels: []
+ upload_or_check_non_existence /recipe_root conda-forge --channel=main
Traceback (most recent call last):
  File "/opt/conda/bin/upload_or_check_non_existence", line 13, in <module>
    from binstar_client.utils import get_binstar
ImportError: cannot import name 'get_binstar'
+ exit 1
Exited with code 1
```

ref: https://github.com/conda-forge/flex-feedstock/pull/18#issuecomment-370015817

cc @ocefpaf

**Comment by abarto** [comment]
Already fixed on the develop branch. It'll be included on the next release.

**Comment by jakirkham** [comment]
Thanks for the update.

Is there a PR or commit that includes the fix?

Is `get_server_api` the recommended approach going forward?

**Comment by abarto** [comment]
get_server_api is the recommended approach as get_binstar was deprecated ages ago. That being said, its removal caused some unintended problems for us as well so we had put it back. Sorry about the inconvenience.

**Comment by jakirkham** [comment]
No worries. Sounds like it was our bad by not using `get_server_api` long ago. Have filed this downstream as issue ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/5 ) so we can fix it.

Thanks for your help.

**Comment by jakirkham** [comment]
So did this land in 1.6.12?

**Comment by jakirkham** [comment]
Proposing we add it back with PR ( https://github.com/Anaconda-Platform/anaconda-client/pull/467 ).

**Comment by abarto** [comment]
@jakirkham No it didn't. I'll release 1.6.13 tomorrow.

**Comment by jakirkham** [comment]
No worries.

FWIW went ahead and put up PRs to fix conda-forge's infrastructure. They can wait for a bit as we are still using the old anaconda-client. That said, the fixes needed to be done and the recent release was a much needed reminder. If you have time to look, would appreciate your feedback. Not sure if anything else needs to be updated (as we don't currently show deprecation warnings 😞).

**Comment by abarto** [comment]
I just tagged the release. It'll hit the main channel tomorrow. Sorry about the confusion.
