### ISSUE TITLE
Wheels upload doesn't work with wheel==0.31.0

### ISSUE THREAD

**Issue by sklam** [Anaconda-Platform/anaconda-client#469]
This issue is observed with anaconda-client==1.6.14 with the recently released wheel==0.31.0

* wheel==0.31.0 removed metadata.json.  See https://github.com/pypa/wheel/issues/195 and https://github.com/Azure/azure-cli-extensions/issues/128.

  When anaconda-client fail to find the metadata, it requests the user to supply `--package` and `--version`.  However, it fails to upload.

* File upload fail quietly

  During uploading of a .whl built with wheel==0.31.0 `file_attrs['basename']` raises a KeyError at
https://github.com/Anaconda-Platform/anaconda-client/blob/e4148d8bdd611de1771f78cba1a5fccd187dd7ee/binstar_client/commands/upload.py#L231
  The error is later suppressed because of:
https://github.com/Anaconda-Platform/anaconda-client/blob/e4148d8bdd611de1771f78cba1a5fccd187dd7ee/binstar_client/scripts/cli.py#L48-L49

**Comment by rohit-jamuar** [comment]
Bump! Is there an estimate by when this issue would be addressed?

**Comment by goanpeca** [comment]
@rohit-jamuar we are working on this. It will be available on the next anaconda-client version to be released in a couple of days

**Comment by rohit-jamuar** [comment]
@goanpeca Thanks! Do you have an exact release date?

**Comment by goanpeca** [comment]
@rohit-jamuar, not an exact date but definitely before August ends!
