### ISSUE TITLE
[ERROR] ('Authorization header was not given', 401)

### ISSUE THREAD

**Issue by tykavanaugh** [Anaconda-Platform/anaconda-client#475]
TyKavanaugh:PI_Spreadsheet_Project BlackBox$ anaconda notebook upload PI_sheet(final).ipynb
-bash: syntax error near unexpected token `('
TyKavanaugh:PI_Spreadsheet_Project BlackBox$ PI_sheet.ipynb
-bash: PI_sheet.ipynb: command not found
TyKavanaugh:PI_Spreadsheet_Project BlackBox$ anaconda notebook upload PI_sheet.ipynb 
Using Anaconda API: https://api.anaconda.org
[ERROR] ('Authorization header was not given', 401)
TyKavanaugh:PI_Spreadsheet_Project BlackBox$ 

Not sure how to fix it or what an "authorization header" is, google turned up nothing relevant.

**Comment by bkreider** [comment]
I'm closing this as stale.  If you are still having problems, I you can open a ticket with conda here: https://github.com/conda/conda/issues.
