### ISSUE TITLE
Text needs an update 

### ISSUE THREAD

**Issue by waqasanjum6** [Anaconda-Platform/anaconda-client#483]
Anaconda-client =1.7.0

Steps to reproduce : 
Run : anaconda --help

Actual Result : Text needs an update 
![screenshot_16](https://user-images.githubusercontent.com/21064071/42893810-c4f2c8a0-8ace-11e8-9055-613d39011188.png)

- Print debug information on the console
- Only show warnings or errors on console

**Comment by goanpeca** [comment]
@waqasanjum6 I don't understand

**Comment by waqasanjum6** [comment]
Sorry for late reply  
1st line :  ot changes to on 
2nd line can be update from " only show warning or errors the console "  to "only show warnings or error on the console "

**Comment by goanpeca** [comment]
Right! thanks
