### ISSUE TITLE
Uploading large batches of packages is problematic due to lack of any `--skip-existing` feature.

### ISSUE THREAD

**Issue by mingwandroid** [Anaconda-Platform/anaconda-client#490]
I was bulk uploading all R stuff but it ran into a package that was already there so it stopped, now, to continue my upload, I am forced to either somehow keep track of what I've already uploaded (I used wildcards here to specify all of them when I uploaded them) or use `--force` (since a load of packages have just been uploaded), but that means I'd could risk changing a sha1 if it exists but was uploaded in a previous session.

Really we need a `--skip-existing` flag rather than exiting immediately.

**Comment by goanpeca** [comment]
@mingwandroid could you provide an example of what your desired use case is, so I can add the feature on the next sprint?
