### ISSUE TITLE
Add --skip-duplicates option

### ISSUE THREAD

**Issue by skrah** [Anaconda-Platform/anaconda-client#491]
I've the following problem (hopefully I haven't overlooked an existing solution):

I need to build multiple packages on travis-ci and upload dev versions only if all builds of the individual packages have succeeded.

The build should be triggered if *one* of the packages has been updated, so several packages may already have an existing anaconda.org upload with the latest version.

I'd like to avoid the `--force` option, because it seems to erase download counts and the new archive has a different sha2sum.

Currently I'm using a hack that checks the existing version on anaconda.org and only attempts the upload if a build has a new version string:

https://github.com/plures/xnd-all/blob/master/scripts/check_upload.py

I wonder if something like this could be integrated as an option to anaconda-upload, say `--skip-duplicates`, which should do nothing and return success if a package with the same version string already exists.

**Comment by mingwandroid** [comment]
Seems this is today's hit issue, I filed this 2 hours ago:

https://github.com/Anaconda-Platform/anaconda-client/issues/490

**Comment by skrah** [comment]
It does look like a fashionable topic, I guess I'll close this one.
