### ISSUE TITLE
Anaconda Verifying Transaction: failed

### ISSUE THREAD

**Issue by Desmond00** [Anaconda-Platform/anaconda-client#504]
Constantly getting error while performing any conda install.
`conda install --force scipy`

Getting these errors:

> Preparing transaction: done
> Verifying transaction: failed
> 
> CondaVerificationError: The package for scipy located at D:\Anaconda\pkgs\scipy-1.1.0-py37h4f6bf74_1
> appears to be corrupted. The path 'Lib/site-packages/scipy/io/tests/data/test-44100Hz-2ch-32bit-float-be.wav'
> specified in the package manifest cannot be found.
> 
> CondaVerificationError: The package for scipy located at D:\Anaconda\pkgs\scipy-1.1.0-py37h4f6bf74_1
> appears to be corrupted. The path 'Lib/site-packages/scipy/io/tests/data/test-44100Hz-2ch-32bit-float-le.wav'
> specified in the package manifest cannot be found.
> 
> CondaVerificationError: The package for scipy located at D:\Anaconda\pkgs\scipy-1.1.0-py37h4f6bf74_1
> appears to be corrupted. The path 'Lib/site-packages/scipy/io/tests/data/test-44100Hz-le-1ch-4bytes-early-eof.wav'
> specified in the package manifest cannot be found.
> 
> CondaVerificationError: The package for scipy located at D:\Anaconda\pkgs\scipy-1.1.0-py37h4f6bf74_1
> appears to be corrupted. The path 'Lib/site-packages/scipy/io/tests/data/test-44100Hz-le-1ch-4bytes-incomplete-chunk.wav'
> specified in the package manifest cannot be found.
> 
> CondaVerificationError: The package for scipy located at D:\Anaconda\pkgs\scipy-1.1.0-py37h4f6bf74_1
> appears to be corrupted. The path 'Lib/site-packages/scipy/io/tests/data/test-44100Hz-le-1ch-4bytes.wav'
> specified in the package manifest cannot be found.
> 
> CondaVerificationError: The package for scipy located at D:\Anaconda\pkgs\scipy-1.1.0-py37h4f6bf74_1
> appears to be corrupted. The path 'Lib/site-packages/scipy/io/tests/data/test-48000Hz-2ch-64bit-float-le-wavex.wav'
> specified in the package manifest cannot be found.
> 
> CondaVerificationError: The package for scipy located at D:\Anaconda\pkgs\scipy-1.1.0-py37h4f6bf74_1
> appears to be corrupted. The path 'Lib/site-packages/scipy/io/tests/data/test-8000Hz-le-2ch-1byteu.wav'
> specified in the package manifest cannot be found.

Tried, 
`conda clean -all and conda clean --all`
`conda clean --packages --tarballs `

Nothing worked.

**Comment by goanpeca** [comment]
@Desmond00 please open this in the correct repo https://github.com/conda/conda
