### ISSUE TITLE
Access denied when trying to run the Anaconda Prompt in Windows 10

### ISSUE THREAD

**Issue by csaiedu** [Anaconda-Platform/anaconda-client#519]
After a failed attempt at upgrading Dash with Conda (I had an error with markupsafe during the install), my paths seem to have been corrupted and when I try to start Anaconda prompt as a user  I get:

> Access is denied.
> The system cannot find the file NAME\AppData\Local\Temp\conda-9307.tmp.
> Could Not Find C:\Users\FIRSTNAME NAME\AppData\Local\Temp\conda-9307.tmp
> 

(Note that there is a space between FIRSTNAME and NAME in the path and I know that has created issues in some post before and I can see that the error seem to pertain to the file starting with NAME only)

When running Anaconda prompt in administrator mode I get 

> activate does not accept more than one argument:
> ['d:\\Software\\Anaconda3', 'NAME\\AppData\\Local\\Temp\\conda-11491.tmp']
> 

I have no idea how to recover from this and restore my original Anaconda Prompt. Is there a place where the default path for the environment could have got corrupted during the installation failure?

Thanks

**Comment by bkreider** [comment]
Can you open this ticket in the Conda issue tracker?  This issue tracker is just for anaconda-client.  Thank you.  

https://github.com/conda/conda/issues
