### ISSUE TITLE
Pygame Anaconda Issue

### ISSUE THREAD

**Issue by Jo-Byr** [Anaconda-Platform/anaconda-client#543]
Hi,
I am trying to download pygame, but knowing I am running on Anaconda, i tried to pass by their site. 
I saw that i had to use the command "conda install -c pygame", it didn't work.
I tried "conda install -c Jo_Byr cogsci pygame" (Jo_Byr) is my username on Anaconda", didn't work either.
Then it was turn of "conda install -c jonat cogsci pygame" (jonat is my computer username), and all variants with jonat, Jo_Byr or none as username and pygame or cogsci pygame for the package, but nothing worked.
I can send screenshots of the anaconda prompt cmd if necessary, just tell me which one.
Thanks in advance, sorry if someone already spoke of this issue, I didn't find anything about it.

Jo-Byr

**Comment by cjmartian** [comment]
try this:

`conda install pygame -c cogsci`
