### ISSUE TITLE
WSL2 conda environment does not recognize Python import of libraries

### ISSUE THREAD

**Issue by Bill-Fujimoto** [Anaconda-Platform/anaconda-client#545]
I installed WSL 2 with Ubuntu 18.04 distro in my Win10 laptop (OS build 19041.207, 2004 preview release).  
From the bash terminal (Windows Terminal),  I installed miniconda in Linux.  Further I installed various libraries into the base env, numpy, pandas, matplotlib, etc.
When I started python from bash terminal, running import numpy [or other libs] throws an error, i.e. it cannot find the libs.
In order to get the new libs recognized, I had to deactivate the base env by issuing $ conda deactivate , then reactivate the environment with $ conda activate,  (if in any other conda evironment, I deactivated 2 times until the base was deactivated).  Once this is done, then python import statements worked properly.
This problem only appeared in WSL2 Linux, normal Windows anaconda prompt has no such issue.

**Comment by dawi9840** [comment]
I have the same issue. 

My situation is I create a Conda virtual environment  with command "conda inttall tensorflow" in WSL 2 with ubuntu18.04 and  enter into the environment try to use python import tensorflow package, however the message always get  "ModuleNotFoundError: No module named 'tensorflow' ". 

On the other hand, I try to exit the Conda virtual environment with command "conda deactivate", then do the install package, which  can use python import the package!

I want to use different package version, therefore I wander to solve this issue.
