### ISSUE TITLE
Unable to run python code

### ISSUE THREAD

**Issue by andriiko489** [Anaconda-Platform/anaconda-client#554]
An error occurred while running my code, which I don't know how to fix.
![Screenshot_20](https://user-images.githubusercontent.com/51889954/98725618-0a53c880-239e-11eb-9ba6-6fc3bd1ff796.png)

**Comment by csoja** [comment]
closing as this issue tracker is for issues that relate specifically to the anaconda-client CLI for anaconda.org and this question does not fall in that category.  
in the above issue, it looks like you are trying to use the conda package and environment manager to run code.  If you haven't already resolved this issue, I'd recommend reviewing the Anaconda documentation (https://docs.anaconda.com/anaconda/user-guide/).
