### ISSUE TITLE
Silent failure to upload on Python 3.9

### ISSUE THREAD

**Issue by ndevenish** [Anaconda-Platform/anaconda-client#555]
See discussion in #501. Hacking in catching of the error that occurs, get:
```
Uncaught exception: module 'base64' has no attribute 'encodestring'
```

This is because of https://github.com/Anaconda-Platform/anaconda-client/blob/ce89e4351eef0f3d2840c713397e013231de25f8/binstar_client/utils/__init__.py#L52 - `encodestring` was removed in python 3.9. https://bugs.python.org/issue39351, and my new `conda-build` environment installed 3.9 by default.

**Comment by chrisjbillington** [comment]
This was fixed in #551, but there hasn't been a release since.
