### ISSUE TITLE
pandas command returns Important Error in Anaconda release 2020.11

### ISSUE THREAD

**Issue by gernot8** [Anaconda-Platform/anaconda-client#558]
pandas command .to_hdf(...) returns _Important Error: Missing optional dependency 'tables'. Use pip or conda to install tables._ in Anaconda release 2020.11.
After deinstalling release 2020.11 and installing again release 2020.02. the code works fine again. Seems to be an issue with the latest release 2020.11.

**Comment by csoja** [comment]
This issue tracker is for the anaconda-client CLI for anaconda.org. Closing.
I'd recommend opening this issue on https://github.com/ContinuumIO/anaconda-issues
