### ISSUE TITLE
Spyder does not open on the graphical interface

### ISSUE THREAD

**Issue by Trincazul** [Anaconda-Platform/anaconda-client#560]
I recently installed anaconda on my macbook air, and I had a problem opening the spider application, it is not opening, so I reinstated the program and then the problem persisted.

can this be some kind of problem related to the system or the installed python conflicting?

is there a command in which I can open the spyder separately from the UI application?

**Comment by csoja** [comment]
This issue should be opened on the anaconda-issues github repository (https://github.com/ContinuumIO/anaconda-issues).  This issue board is for issues that pertain specifically to the anaconda-client CLI for anaconda.org.
