### ISSUE TITLE
`anaconda copy --replace` did not actually replaced old packages

### ISSUE THREAD

**Issue by malfet** [Anaconda-Platform/anaconda-client#581]
`anaconda copy malfet/torchvision/0.10.0 --replace --to-owner pytorch` were used to replace packages with extraneous dependency to the ones without it. But apparently this command just updated the metadata, while links to packages in CDN still pointed to the old version, which were reported in https://github.com/pytorch/vision/issues/4261 and https://github.com/pytorch/vision/issues/4262

Expected outcome: `anaconda copy --replace` should either update the packages or return an error if it could not be done for some reason.
Workaround: Deleting old version of packages first and then copying new ones resolved the issue.

**Comment by bkreider** [comment]
I'm closing this as stale. If this is still a problem, please reopen. 

This sounds like a CDN cache invalidation problem on the anaconda.org side and not an anaconda-client issue.  I believe some of those bugs have been addressed in the last few months to properly invalidating and recaching in cloudflare.
