### ISSUE TITLE
MVIC camera model ambiguity

### ISSUE THREAD

**Issue by drschenk** [Anaconda-Platform/anaconda-client#607]
In the NH lorri camera model we found that a vector element sign had to be flipped because of the way the fits files were read out vs isis was mirrored.  I’ve been wondering if we need to do the same for mvic frames and scans of Pluto.   believe e the FITS files are read out in the same way (mirrored left-right) but am not sure and dont know which elements in which kernels would need to be changed to test this?   The root problem is that the values for control points and stereo DEMs are coming out with high residuals or warped if MVIC images are used in the solutions.  Same question for framing and scan modes as I think the camera model is basically the same.  I’ve been stabbing the dark but not sure which kernels have all the required parameters and which parameters need flipping if any, but not finding the solution. 

(mostly for Stuart S.)

**Comment by bkreider** [comment]
I'm not sure what this has to do with anaconda-client.
