### ISSUE TITLE
Status 405 when attempting to upload packages

### ISSUE THREAD

**Issue by seemethere** [Anaconda-Platform/anaconda-client#619]
We're currently seeing failures across our release pipelines relating to a 405 status like so:

```
> anaconda upload -u pytorch-nightly --force pytorch-1.13.0.dev20220817-py3.7_cpu_0.tar.bz2
Using Anaconda API: https://api.anaconda.org
Using "pytorch-nightly" as upload username
Processing 'pytorch-1.13.0.dev20220817-py3.7_cpu_0.tar.bz2'
Detecting file type...
File type is "Conda"
Extracting conda attributes for upload
Creating package "pytorch"
Creating release "1.13.0.dev20220817"
Uploading file "pytorch-nightly/pytorch/1.13.0.dev20220817/linux-64/pytorch-1.13.0.dev20220817-py3.7_cpu_0.tar.bz2"
[WARNING] Distribution "linux-64/pytorch-1.13.0.dev20220817-py3.7_cpu_0.tar.bz2" already exists. Removing.
 uploaded 83283 of 83283Kb: 100.00% ETA: 0.0 minutes
[ERROR] ('Method Not Allowed: Specified method is invalid for this resource. ([POST] https://api.anaconda.org/commit/pytorch-nightly/pytorch/1.13.0.dev20220817/linux-64/pytorch-1.13.0.dev20220817-py3.7_cpu_0.tar.bz2 -> 405)', 405)
```

These previously passed and no code change has occurred on our side and the token we are utilizing is not expired.

Did something change about the permissions level for the `/commit/` endpoint that is now causing it to 405?

**Comment by seemethere** [comment]
I can also see that the package itself gets uploaded, just that the `/commit/` endpoint is throwing a 405

**Comment by matthewfeickert** [comment]
[This is also happening to `matplotlib`](https://gitter.im/matplotlib/matplotlib?at=62fc4f1d7ccf6b6d453d0259), but after the 405 gets thrown then things error out and all remaining uploads never happen.

**Comment by matthewfeickert** [comment]
@seemethere in the event that you're interested I've [opened up a topic on the Anaconda Nucleus product help forums](https://community.anaconda.cloud/t/uploads-of-packages-to-anaconda-cloud-failing-with-405-status/31498), as I'm not sure where else to contact support.

**Comment by matthewfeickert** [comment]
@seemethere this seems to have been resolved on the Anaconda side for `matplotlib`. Are things solved for `torch` as well?

**Comment by seemethere** [comment]
Yup appears to have been resolved, going to close but it'd be good to get some clarity from the Anaconda team why this happens.
