### ISSUE TITLE
Replacing vendored appdirs (deprecated upstream) with platformdirs

### ISSUE THREAD

**Issue by mbargull** [Anaconda-Platform/anaconda-client#692]
@jezdez is currently replacing `appdirs` in `conda` (also vendored) with `platformdirs` (upstream's recommended successor).

Changes very similar to those in https://github.com/conda/conda/pull/13307 could be done for `binstar_client.utils.config`, too.

refs:
    - https://github.com/conda/conda/pull/13307
    - https://github.com/conda/conda/issues/13306
    - https://github.com/ActiveState/appdirs/commit/8734277956c1df3b85385e6b308e954910533884

**Comment by mbargull** [comment]
Resolved by gh-693.

**Comment by s22chan** [comment]
This needs to be released or users have to symlink or downgrade conda.

see https://github.com/conda/conda/issues/13517
