### ISSUE TITLE
Remove collections subcommand

### ISSUE THREAD

**Issue by teoliphant** [Anaconda-Platform/anaconda-client#75]
As collections are no longer a part of the binstar web-site, the collections subcommand from binstar should be removed --- and replaced with channels.

**Comment by pelson** [comment]
I notice that one of the scopes available for new tokens is "collections":

```
$ anaconda auth --list-scopes
...
repos:collection:<COLLECTION_NAME>
  Allow access to specific collection
```

Based on this issue, I presume this functionality is no longer a concept which is available for use? I'm looking for the ability to generate a token which can modify only a subset of an organisation's channel. It appears that this may be possible on a per user basis (within the team), but not on a per-token basis. Is there any such capability?
