### ISSUE TITLE
Better error message in event of token revokation

### ISSUE THREAD

**Issue by LilaHickey** [Anaconda-Platform/anaconda-client#90]
At present if a token is revoked, the user will see the following message on attempting to access the channel:

```
Fetching package metadata: .Error: HTTPError: 401 Client Error: UNAUTHORIZED: https://conda.binstar.org/t/pqVskkFiygzj/anaconda-server/osx-64/
```

Probably it would be good to make it clear in this message that the user's access has been revoked, and that this is not any kind of server error.

**Comment by drf5n** [comment]
Which user?  The client or the token-revoker?   I get something similar with:

       $ conda install -c https://conda.binstar.org/jjhelmus pyproj 
    Fetching package metadata: ....Error: HTTPError: 401 Client Error: UNAUTHORIZED: https://conda.binstar.org/jjhelmus/noarch/
