### ISSUE TITLE
Expiration warning for tokens

### ISSUE THREAD

**Issue by LilaHickey** [Anaconda-Platform/anaconda-client#91]
Related to issue #90, might be useful to warn users about an impending token expiration?  Maybe a month out, they get a warning message when accessing the channel, telling them that the token is expiring soon.

**Comment by emirot** [comment]
Is there a way to know the expiration date of a token via the UI or CLI ? I'm having an issue on ```bash
Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda)... , 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t``` on conda 4.2.9 
Login using anaconda client doesn't help, the only workaround I found is to remove my channel to the ~/.condarc file.
